# Generated by Django 2.2 on 2022-12-28 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.BaseModel')),
                ('name', models.CharField(max_length=64, verbose_name='course name')),
                ('descr', models.CharField(max_length=400, verbose_name='course description')),
                ('learn_times', models.IntegerField(default=0, verbose_name='courses time min')),
                ('degree', models.CharField(choices=[('e', 'easy'), ('m', 'medium'), ('h', 'hard')], max_length=1, verbose_name='course level')),
                ('students', models.IntegerField(default=0, verbose_name='student number')),
                ('fav_num', models.IntegerField(default=0, verbose_name='favorite number')),
                ('click_num', models.IntegerField(default=0, verbose_name='click times')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='course pict')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click time')),
                ('category', models.CharField(default='backend', max_length=20, verbose_name='courses category')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='course tag')),
                ('youneed_know', models.CharField(default='', max_length=300, verbose_name='must know about course')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name='advice')),
                ('detail', models.TextField(default='', verbose_name='course detail')),
            ],
            options={
                'verbose_name': 'course information',
                'verbose_name_plural': 'course information',
            },
            bases=('users.basemodel',),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.BaseModel')),
                ('name', models.CharField(max_length=100, verbose_name='lesson name')),
                ('learn_time', models.IntegerField(default=0, verbose_name='learning time')),
                ('parent_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'verbose_name': 'course lessons',
                'verbose_name_plural': 'course lessons',
            },
            bases=('users.basemodel',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.BaseModel')),
                ('name', models.CharField(max_length=100, verbose_name='lesson name')),
                ('learn_time', models.IntegerField(default=0, verbose_name='learning time')),
                ('url', models.CharField(max_length=200, verbose_name='visit url')),
                ('parent_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson')),
            ],
            options={
                'verbose_name': 'lesson video',
                'verbose_name_plural': 'lesson video',
            },
            bases=('users.basemodel',),
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.BaseModel')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='source file')),
                ('parent_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course material',
                'verbose_name_plural': 'course material',
            },
            bases=('users.basemodel',),
        ),
    ]
